### ISSUE TITLE
bug:  dropped blockchain events can lead to divergent network state

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#12]
There is a race condition with the current implementation of the Engine which can lead to a divergent network state among nodes breaking the principle of eventual consistency. The problem goes like this: 

1. At block 100, @alice changes her signer to `0xf00` 
3. At block 110, @alice changes her signer to `0xbar`
4. Node A receives the signer change `0xf00` but not the one to `0xbar`
5. Node B receives both signer changes
6. Alice broadcasts a new chain with a root set to 120, but accidentally signs it with `0xf00` (invalid root)
7. Node A accepts this message from Alice, but Node B rejects it
8. Later, Node A receives the signer change  

At this point, Node A has one valid chain more than Node B and the nodes will never converge. This is a likely scenario since most blockchain event subscriptions are done over websockets, which do not have strong delivery guarantees and can drop events.

### Proposed Solution
Since we cannot rely on websockets, we have to implement a polling mechanism to ensure that we collect events even if the websocket fails. A pseudo-code implementation of the polling algorithm with be: 

1. Set lastPolledBlock to 0
2. Ask the ETH node for lastKnownBlock 
3. Ask the ETH node for all events between lastPolledBlock and (lastKnownBlock - 3) (for safety)
4. Set lastPolledBlock to lastKnownBlock - 3 
5. Repeat 2 - 4 as needed

We don't need to simulate this exactly, but we should assume that the engine may receive events out of order and so we should be able to handle that gracefully. There are two approaches: 

1. *Accept First, Reject later* -- in this approach, the engine will accept any signed chain that appears valid, but when it receives a new event that might change the validity of a previous chain it re-examines all of them and drops invalid changes. This is simple to implement, but leads to more state reversal which can cause further complexity for clients and entities interacting with nodes. 

2. *Reject First, Accept Later* -- in this approach, the engine keeps track of the lastPolledBlock and only accepts signed chains that are signed with blocks that are equal to or below this. This means that nodes will reject some number of messages if they are received too early. This slows down eventual consistency, but avoids state reversal meaning that it is very unlikely that a chain will be accepted and rejected in the future. The other downside of this approach is that it exposes the engine to more state. 

Next Steps: 

- Decide which approach to take
- Implement the logic in the `addRoot` and `addSignerChange` methods and write unit tests to cover these cases

**Comment by varunsrin** [comment]
the part about roots is no longer relevant, but the general problem still exists

**Comment by pfletcherhill** [comment]
Assigning this to myself, because it should be addressed in the signer set changes

**Comment by pfletcherhill** [comment]
This problem will be solved at the network layer by syncing ID Registry events between hubs. Validation of contract events can be done using the [`validateIDRegistryEvent` method](https://github.com/farcasterxyz/hub/blob/main/src/provider/idRegistryProvider.ts#L56) in the IDRegistryProvider if a hub uses a provider.

**Comment by pfletcherhill** [comment]
Closing this issue because it has been addressed via the SignerSet changes
