### ISSUE TITLE
feat: user data crdt

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#120]
**What is the feature you would like to implement?**
Add a metadata set that syncs user level key value data like 

**Why is this feature important?**
This feature is a pre-requisite for Phase 2, since without this there is no way for a user to indicate their display name or pfp which are important primitives. 

**Will the protocol spec need to be updated??**
Will require a new entry in Section 4

**How should this feature be built? (optional)**
TBD

**Additional context**

Desirable data includes: 

- Profile Picture
- Display Name
- A short text bio
- A simple location field
- A complex, temporal location field (currently at)
- NFT metadata (show these, hide these) 
- Links to other social networks, applications (e.g. Github, Twitter)

**Comment by pfletcherhill** [comment]
Implemented by https://github.com/farcasterxyz/hub/pull/195
