### ISSUE TITLE
feat: increase cast length to 320 characters

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#121]
**What is the feature you would like to implement?**
Allow cast length to be increased to 320 characters.

**Why is this feature important?**
The current limit of 280 characters is somewhat arbitrary and not designed to optimize for the type of content we want on the network. Using a larger cast length might capture more of the distribution of casts and discourage the use of threading (see supporting data below). 

**Will the protocol spec need to be updated??**
The requirements in the Cast section under (4) will need to be updated

**Comment by varunsrin** [comment]
Collecting stats on distribution of current cast sizes: 

```
  0 -70	76844
 71-140	70115
141-210	21163
211-280	19124
```

**Comment by varunsrin** [comment]
Extension to 512 characters is both excessive (for current behaviors) and inadequate (for capturing screenshot essays). Instead we propose a more modest increase to 320 characters  (a 15% increase) which should capture more of the long tail of thoughts, while marginally reducing the need to use threads.

**Comment by whatrocks** [comment]
But wouldn't 420 be funnier?

I'll update PRs tonight!

**Comment by varunsrin** [comment]
saving that joke for a future upgrade
