### ISSUE TITLE
feat: ensure all SignatureAlgorithm.EthereumPersonalSign signatures comply with EIP-712

### ISSUE THREAD

**Issue by pfletcherhill** [farcasterxyz/hub#136]
**What is the feature you would like to implement?**
See https://eips.ethereum.org/EIPS/eip-712

**Why is this feature important?**
Wallets should render Farcaster-related signature requests in a nice, clear way

**Comment by varunsrin** [comment]
see doc for more details: https://www.notion.so/farcasterxyz/EIP-712-for-Verified-Addresses-80a0a638119a41bfb638d08a62d04201

**Comment by pfletcherhill** [comment]
Implemented by https://github.com/farcasterxyz/hub/pull/188 and https://github.com/farcasterxyz/hub/pull/218
