### ISSUE TITLE
chore: enable noPropertyAccessFromIndexSignature and noUncheckedIndexedAccess

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#151]
Enable the following checks, which requires some code to be modified: 

1. `noPropertyAccessFromIndexSignature` - when accessing a prop that may not exist, forces usage of the `object['prop']` instead of `object.prop`

2. `noUncheckedIndexedAccess` - when accessing an object with unknown keys but known types, the value is returned as `type | undefined` instead of type, which forces handling the undefined case downstream

**Comment by adaddeo** [comment]
1 should be easy.
2 will require making decisions about how to handle undefined values. 

For 2, I'd suggest that in test files `as` is used to make the compiler happy while avoiding unnecessary complexity to narrow the value at runtime. 

In non-test files it's likely best to handle each situation on a case by case basis. In most narrowing the type with a run-time check that accurately handles undefined values will be a good idea. In others, especially where the data is known to be non-empty, the blast radius might be too large to justify the complexity it may be preferred to hint to TS compiler directly.

Thoughts?

**Comment by varunsrin** [comment]
I think that's a reasonable approach - I would suggest doing them as two separate PR's if you are taking this on.

**Comment by adaddeo** [comment]
see #260 and #261
