### ISSUE TITLE
feat: replace SimpleSync with SnapshotSync

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#155]
**What is the feature you would like to implement?**
When Hubs start up, they should be able to download state from a snapshot of RocksDB stored on S3

**Why is this feature important?**
This replaces SimpleSync, which might not be feasible to keep running as the network grows since it places a heavy load on syncing with a specific Hub. 

**Will the protocol spec need to be updated??**
Yes, the sync section should be updated.

**Comment by sanjayprabhu** [comment]
I think this was closed accidentally, the linked PR replaced simple sync with diff sync. But we still need to implement snapshot sync from s3.

**Comment by adityapk00** [comment]
Decided to not do snapshot sync, and depend on the regular sync instead.
