### ISSUE TITLE
feat: addressing nodes

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#157]
**What is the feature you would like to implement?**
A concise, high level summary of the feature 

**Why is this feature important?**
An argument for why this feature should be build and how it should be prioritized

**Will the protocol spec need to be updated??**
Call out the sections of the [protocol spec](https://github.com/farcasterxyz/protocol) that will need to be updated (e.g. Section 4.3 - Verifications, Section 3.1 - Identity Systems) 

**How should this feature be built? (optional)**
A design for the implementation of the feature

**Additional context**

**Comment by sagar-a16z** [comment]
Speculating here, but I think this issue was talking about how nodes would discover and connect with each other. 

We have that problem mostly solved with bootstrapping, gossipSub discovery, and gossip based Contact sharing (https://github.com/farcasterxyz/hub/pull/220).
