### ISSUE TITLE
bug: readme instructions missing details on creating identity

### ISSUE THREAD

**Issue by FreeTrade** [farcasterxyz/hub#182]
Following errors on Test/Start - any thoughts?

C:\Users\Cash\farcaster3>yarn install
yarn install v1.22.19
warning package.json: License should be a valid SPDX license expression
warning ..\package.json: No license field
warning hub@1.0.0: License should be a valid SPDX license expression
[1/5] Validating package.json...
warning hub@1.0.0: License should be a valid SPDX license expression
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 99.31s.

C:\Users\Cash\farcaster3>yarn test
yarn run v1.22.19
warning package.json: License should be a valid SPDX license expression
warning ..\package.json: No license field
$ NODE_OPTIONS=--experimental-vm-modules jest
'NODE_OPTIONS' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\Cash\farcaster3>yarn start
yarn run v1.22.19
warning package.json: License should be a valid SPDX license expression
warning ..\package.json: No license field
$ tsx src/cli.ts start
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at __node_internal_captureLargerStackTrace (node:internal/errors:484:5)
    at new NodeError (node:internal/errors:393:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1026:11)
    at defaultResolve (node:internal/modules/esm/resolve:1106:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at h (file:///C:/Users/Cash/farcaster3/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:2279)
    at async nextResolve (node:internal/modules/esm/loader:163:22)
    at async ESMLoader.resolve (node:internal/modules/esm/loader:841:24)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at Command.<anonymous> (C:\Users\Cash\farcaster3\src\cli.ts:51:24) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

Node.js v18.12.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by FreeTrade** [comment]
I played around with the paths a little, and eventually got - 

[Error: ENOENT: no such file or directory, open 'C:\Users\Cash\farcaster3\.hub\default_id.protobuf'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Cash\\farcaster3\\.hub\\default_id.protobuf'
}

What's this default_id.protobuf file? Do I need it to start?

**Comment by FreeTrade** [comment]
Same error on Ubuntu -

[Error: ENOENT: no such file or directory, open '/root/hub/.hub/default_id.protobuf'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/hub/.hub/default_id.protobuf'
}

**Comment by varunsrin** [comment]
@sagar-a16z may need to add instructions for the new id generation to the README

**Comment by payton** [comment]
@FreeTrade you can run `yarn identity` to create a peerID. This is from libp2p.

**Comment by FreeTrade** [comment]
Ok, done - it's starting up now successfully - doesn't seem to be connecting to anything yet.

**Comment by varunsrin** [comment]
the hubs are still a work in progress, this milestone tracks the remaining items that need to be shipped before all the peering works end to end: https://github.com/farcasterxyz/hub/milestones

**Comment by FreeTrade** [comment]
I understand the the hub does not peer automatically yet - I was hoping there is way to manually add peers as I'd like to get started building a client asap.

**Comment by varunsrin** [comment]
the easiest way to do this until the hubs are ready are the use the merkle apis which are bridging data from v1 to v2 

https://www.notion.so/farcasterxyz/Merkle-API-v2-0edc8911f011433182be024d02a17b07

**Comment by FreeTrade** [comment]
Thanks, while this does look like the easiest way rn, I'd anticipate having to re-engineer when the hubs are functional. I'll wait for that rather than engineering twice.
