### ISSUE TITLE
Some tests timeout

### ISSUE THREAD

**Issue by adityapk00** [farcasterxyz/hub#269]
**What is the bug?**
There are 4 tests that always timeout on my Mac (2018 Intel i9 8C/16T), and an additional 5 that occasionally timeout. 

The 4 that always timeout are:
- `node.test.ts`
- `rpc.test.ts`
- `engine.mock.test.ts`
- `hub.test.ts`

However, increasing the timeout to 30s makes all tests pass. 

**How can it be reproduced? (optional)**
Running `yarn test` reproduces the issue 100% of the time on my machine. 

**Additional context (optional)**
I've made a PR to simply increase the timeout to 30s, but there may be an underlying issue that is causing the timeouts.

**Comment by varunsrin** [comment]
@adityapk00 this may be resolved now with my recent test improvements. lmk if you are still seeing the issue

**Comment by adityapk00** [comment]
This seems to have fixed it.
