### ISSUE TITLE
feat: support nft urls in reactions and replies

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#280]
**What is the feature you would like to implement?**

Allow reactions and cast-replies to point to an NFT as their parent. We will eventually want to expand this to work for generic web URLs as well, though that can be cut if it adds a lot of complexity. 

**Why is this feature important?**

Merkle supports NFT likes in a centralized manner, and NFT comments is one of the most requested features from users. If the protocol doesn't support it, clients will continue doing it in a centralized manner. Doing it in a decentralized way, makes this data more portable and available to other clients. 

**Will the protocol spec need to be updated??**

Yes, we'll need to change the specification for the message fields for cast parents and reaction targets. 

**How should this feature be built? (optional)**

TBD

**Comment by pfletcherhill** [comment]
Closing in favor of existing ticket https://github.com/farcasterxyz/hub/issues/231
