### ISSUE TITLE
bug: consistency issues with messages in cast threads

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#31]
### Problem
Take a cast thread that has 4 layers:  OP, child, gchild, ggchild. Each child cast is linked to its parent which eventually connects back to the OP. This creates a couple of problems: 

1. If the child cast goes missing from the network then the gchild and the ggchild are left in a dangling state and can never be associated back to the thread. 

2. If the child was written by bob, and the node has chosen not to subscribe to bob, it could not construct the thread without fetching bob's child message from his server. 

Ideally, clients would always be able to reconstruct the thread and show missing messages accordingly. 

### Proposed Solution

We introduce a new cast sub type (reply cast) that must contain:

1. A URI reference to the parent (present today)
2. A URI reference to the thread OP
3. A generation clock which increments with every generation (child = 1, gchild = 2 etc.) 

Nodes currently merge a thread sequentially from OP to ggchild, they can now do it in parallel after ingesting the OP.  They can also skip messages from users they don't subscribe to. Our data storage requirements go up 48 bytes a cast and we have a few more checks in our merge set. 

### Counter Proposal A

The alternative is to stick with the current approach where he gchild if the child cannot be provided. Messages in a thread will always propagate in a consistent state or not at all, at the expense of making the sync process less parallelizable within threads. This solves (1) and possible even reduces the occurrence of inconsistency issues which would be helpful for clients. 

It does not solve (2) since bob's message would never be ingested. In this case, the node sync would have to specially fetch bob's message using the URI provided in order to construct the thread. It does not need to retain the whole message once verified, just enough to construct the thread. 

The main argument against this approach is that it forces us to choose between no sharding (i.e. you can't ignore bob) which is undesirable for scaling or having dependencies on messages from users nodes don't care about, which can create more choke points when syncing data.

**Comment by sds** [comment]
Regarding:
>We introduce a new cast sub type

Alternatively, we could define a single cast type that includes all the necessary information so we don't need to define multiple types. An original cast has a generation of `0`, the thread OP merkle root is its own merkle root, and there is no reply parent defined.

Unless we expect a lot more functionality to be present in a reply cast vs an original cast, perhaps there's no need to define a separate cast type as it would just introduce complexity in the protocol.

Were there other reasons we might want a separate type?

**Comment by varunsrin** [comment]
The primary argument for not requiring props would be space savings. Adding the generation and merkle root would is an extra 90 bytes on top level messages. If you assume each DAU has 2 OP posts per day at 10k DAU's you need (90 * 2 * 365 * 10000) / (1024^2) = ~ 625 MB per year per node.

**Comment by sds** [comment]
Sorry, I wasn't being clear. What I mean is that the TypeScript type would simply include _optional_ keys like `conversationMerkleRoot`,`replyParentMerkleRoot`, and `generation`. This way you still have a single "type" (from a TypeScript-centric viewpoint) but the protocol can then infer that the lack of any of these keys means the cast is an OP. There's no additional data that needs to be stored, and we're able to use the same type for both OPs and replies.

**Comment by varunsrin** [comment]
Yes, supportive of optional properties.

**Comment by varunsrin** [comment]
On further reflection, the proposed solution has more downsides that make it undesirable: 

1. The `parent` (URI reference to the direct parent) and `root` (URI reference to the thread OP) can come into conflict if root is accidentally or intentionally pointed at a cast that is in a different branch than the parent. There are cases where we cannot deterministically know this (e.g. if an ancestor of the the parent and the conflicting root are both excluded because of sharding). 

2. The generation clock can similarly create conflicts that are hard to check if set incorrectly by the client. 


I propose closing this issue and reverting to the behavior of not rendering dangling messages in a thread. In many cases, they are irrelevant without the parent. These messages should still be synced and preserved so that the URLs to them will stay valid.

**Comment by varunsrin** [comment]
@pfletcherhill and @danromero  here is a simple example illustrating an edge case where a malicious actor can create confusion by retracting their messages from a thread in a case where the root is available. 

<img width="1462" alt="Screen Shot 2022-10-05 at 1 09 27 PM" src="https://user-images.githubusercontent.com/528882/194153561-dedeed9f-47f7-486b-8863-050f11e90994.png">

If the root property is made available, clients will almost certainly attempt to implement rudimentary threading where floating messages are displayed. In most cases, these are fine but in some rare cases they can lead to catastrophic confusion which undermines trust in clients, and by extension, the network. 

My view is that the protocol/hubs should take a stricter approach only claiming that something is part of a thread if the entire conversation is visible and there is no potential for confusion about the intent behind messages. (i.e., close this ticket and do not add the `root` / reference to thread OP) 

The downside of this approach is that: 

1. A missing child cast can permanently disconnect a grand-child+ reply from the parent
2. Hubs will have to do more work to construct threads - every time a new message appears we have to look at all disconnected messages to see if any of them have a connection to this message. With a root, we would scan a much smaller set to make that determination. 

It is possible (but not certain) that there is a more elegant datastructure that could make stronger guarantees about the exact position of a cast in a tree even if all the other messages were missing. If such a data structure is feasible it would alleviate (1) and (2). But this will take a long time to get right, and we should extend the protocol if/when it is discovered.

**Comment by varunsrin** [comment]
after further discussion, we've decided to close this ticket. 

the tradeoff is that hubs will not, at least for the current version, offer threading API's which must be constructed by an indexer that sits on top of a hub.
