### ISSUE TITLE
feat: message model constructors 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#337]
**What is the feature you would like to implement?**

Methods that will construct a correctly signed MessageModel of a specific type given a set of parameters or a simple object. For example, calling `makeSignerAdd()` with the right parameters should produce a SignerAdd message correctly. This is a higher order abstraction over the Flatbuffer builders that also handles the correct hashing and signing of objects using the appropriate libraries. 

**Why is this feature important?**

Farcaster applications will model user actions as JSON objects which must be converted into a Flatbuffer representation before being sent to the Hub. By providing a standardized library in the ~/flatbuffers/ folder which is exported along with the RPC Client we can make it easy for clients to generate these messages correctly. 

**Will the protocol spec need to be updated??**

No

**How should this feature be built? (optional)**

Imagine that the consumer of this library is an application that hosts thousands of users and wants to generate messages for them. We would like the interface to: 

- Be as ergonomic as possible given the consumer's needs. For example, it might allow an instance to be create that remembers the signing key, so that it can be easily invoked with new parameters instead of having to respecify the key each time. 

- Be extremely strict, so that any additional parameters or data provided will fail noisily, which will make debugging easy. 

- Be thoroughly tested, down to the exact bytes being output so that we can make changes to the logic without worrying about about introducing subtle byte ordering bugs. 

- Be easily exportable, having no internal dependencies outside of the flatbuffers folder (external deps are OK). 

**Additional Context**

Flatbuffer factories already construct messages given a set of parameters, but this is not ideal outside of a testing environment. Some features like auto population of values when not supplied could lead to subtle and hard to debug errors, and they also have a lot of dependencies that we shouldn't add into production environments.

**Comment by varunsrin** [comment]
@adaddeo this might be a good one for you to pick up if you're interested

**Comment by adaddeo** [comment]
@varunsrin yes I'll pick it up

**Comment by adaddeo** [comment]
Thought: since Farcaster applications will be working with objects from `flatbuffers/models` (i.e. `MessageModel`), it may be worthwhile to break out the RocksDB functionality to avoid having application code with a rocksdb dependency and objects that expose rocksdb specific methods.

**Comment by varunsrin** [comment]
yes, i think thats a good call. 

tagging @pfletcherhill who may have opinions on how to do this

**Comment by adaddeo** [comment]
closed by #355
