### ISSUE TITLE
feat: change message hash digest size from 128-bit to 160-bit

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#438]
**What is the feature you would like to implement?**

Message hashes should be increase to 160-bit from 128-bit. This includes the hash property on the message but also derived properties like tsHash fields in CastRemove and the hashes used in the sync tree. We should also label the enumeration for the has type to include the digest size in the name, in case we launch a blake3 variant with larger hashes in the future. 

**Why is this feature important?**

Shorter 128-bit Blake3 hashes can be broken in a year by a determined attacker with a 5-10M budget, while 160-bit hashes would still take a thousand years and require a budget 50x larger.  The math is outlined here: https://hackmd.io/@farcasterxyz/rkxmwFrBo#Modelling-the-Attack-Vector

**Will the protocol spec need to be updated??**

Yes

**Comment by pfletcherhill** [comment]
Implemented here: https://github.com/farcasterxyz/hub/pull/441
