### ISSUE TITLE
Add blockhash to Verification Claim

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#55]
All Ethereum address verification claims should include a blockHash from the most recent Ethereum block. 

The blockhash helps order verifications which is useful when the same address is found to be verified to multiple Farcaster ID's. Ordering allows applications to resolve conflicts easily, and lets users nullify older verifications by issuing new ones with a more recent blockhash. The protocol itself does not verify or validate the blockHash's, that's entirely up to client applications.

**Comment by pfletcherhill** [comment]
Implemented https://github.com/farcasterxyz/hub/pull/75
