### ISSUE TITLE
SignedMessages should have a network identifier

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#56]
Each signed message should contain an identifier to indicate which network it was intended for. Roughly, we might have a mainnet, testnet and devnet though these names can change and more may be added later.

**Comment by pfletcherhill** [comment]
Do you think it's better to use a byte or just add another attribute to the message body? Byte is more performant, but early on it will be easier to explain and read the extra attribute.

**Comment by varunsrin** [comment]
Agree, for now it should be an attribute. I'll update the ticket to reflect this

**Comment by pfletcherhill** [comment]
Implemented https://github.com/farcasterxyz/hub/pull/92
