### ISSUE TITLE
Track follows in an LWW set 

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#60]
**What is the feature you would like to implement?**
Hubs should track "follows" which is an [action](https://github.com/farcasterxyz/protocol#42-actions) that users should be able to perform

**Why is this feature important?**
We need this in v2 so that all applications can create and read follow relationships established in other applications.

**Will the protocol spec need to be updated??**
Section 4.2 will need to be updated with the specifics of the set and reconciliation

**How should this feature be built? (optional)**
TBD

**Comment by pfletcherhill** [comment]
Implemented https://github.com/farcasterxyz/hub/pull/77
