### ISSUE TITLE
feat: persistent storage for hub data

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#61]
Hub data should be persisted to a reliable data store like Postgres, Redis or equivalent. 

This is important for v2 because the Hub needs to be run as a service in the cloud that can be restarted. The correct long term design might be to use a low-level kv-store like rocksdb or levelsdb, but we're ok cutting corners a bit to ship quickly and then refactor it on later. It's important that we use a simple querying and table layout so that we can migrate later when necessary.

**Comment by pfletcherhill** [comment]
Rocksdb implemented with https://github.com/farcasterxyz/hub/pull/107
