### ISSUE TITLE
Ingest contract events from ethereum nodes

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#63]
Hubs should ingest events from the IDRegistry and NameRegistry contracts via a JSON-RPC endpoint and populate the SignerSets correctly.

**Comment by pfletcherhill** [comment]
A big chunk of this was merged in with the signer set https://github.com/farcasterxyz/hub/pull/38

Left to do:
* [ ] Add a service that watches a specified contract for relevant events
* [ ] Have the engine validate `IDRegistryEvent` objects that it is passed using a web3 provider

Worth mentioning that both of these should be optional for hubs, so a hub can still run offline.

**Comment by pfletcherhill** [comment]
Implemented https://github.com/farcasterxyz/hub/pull/86
