### ISSUE TITLE
feat: denoting fid mentions clearly in cast text

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#79]
**What is the feature you would like to implement?**
A distinct way to format a fid mention within a cast body text so that it can be parsed by clients

**Why is this feature important?**
When a user mentions someone, the protocol specifies that their fid should be tagged (e.g. `91293`). But we need a special way to mark fids so that they do not collide with numbers or with fnames which can technical be numbers as well.  

**Will the protocol spec need to be updated??**
Yes, we will need to update the short cast part of the specification

**How should this feature be built? (optional)**
TBD

**Additional context**

**Comment by pfletcherhill** [comment]
Should implement https://github.com/farcasterxyz/protocol/issues/30
